### ISSUE TITLE
 sensor.updateData();  but is protected and will not compile

### ISSUE THREAD

**Issue by RudyFiero** [Avarupt/Avarupt_TTP229#1]
In NeoPixelDemo you have the following call.
```
void loop() {
 sensor.updateData();//This is called to poll the ttp229 sensor every loop
```
But in Avarupt_TTP229.h you have
```
protected:
    void updateData();
```
and that results in a compile error.

```
Avarupt_TTP229-master/Avarupt_TTP229.h:63:10: error: 'void Avarupt_TTP229::updateData()' is protected

     void updateData();

          ^

NeoPixelDemo:18: error: within this context
```

**Comment by ctjet** [comment]
Currently this project is sitting by the wayside but if you want to try to fix that issue be my guest. Last I remember it worked but I could have accidentally pushed a bad update.

**Comment by RudyFiero** [comment]
Just commenting out the line  
`// protected:  `
fixes the problem for me.  Now it compiles.
